name: CosineAI Twitter → Telegram Notifier

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours

permissions:
  contents: write  # allow committing state back to repo

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitor
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
        run: |
          python monitor.py

      - name: Commit state if changed (with rebase)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add state/last_seen.json
            # Commit locally (may be noop if nothing staged)
            git commit -m "chore(state): update last seen tweet id [skip ci]" || true
            # Rebase on top of latest remote to avoid non-fast-forward
            git pull --rebase origin "$(git rev-parse --abbrev-ref HEAD)" || true
            # Use --force-with-lease to safely update if rebase changed history
            git push --force-with-lease
          else
            echo "No state changes to commit."
          fi